export const en = {
  contentTab: 'Content', seoTab: 'SEO', seo: 'SEO', general: 'General', canonical: 'Canonical', robots: 'Robots', openGraph: 'Open Graph', twitter: 'X / Twitter', schema: 'Schema', previews: 'Previews',
  title: 'Title', description: 'Description', focusKeyword: 'Keywords', defaultKeywords: 'Default keywords', keywordsDescription: 'Separate keywords with ",".', image: 'Image', card: 'Card',
  canonicalMode: 'Canonical mode', canonicalUrl: 'Canonical URL', auto: 'Auto', manual: 'Manual', none: 'None',
  robotsIndex: 'Index directive', robotsFollow: 'Follow directive', index: 'Index', noindex: 'No index', follow: 'Follow', nofollow: 'No follow',
  inherit: 'Inherit', indexFollow: 'Index, follow', noindexFollow: 'No index, follow', indexNofollow: 'Index, nofollow', noindexNofollow: 'No index, nofollow', customDirectives: 'Custom directives',
  summary: 'Summary', summaryLargeImage: 'Summary large image',
  schemaType: 'Schema type', schemaOverrides: 'Schema overrides', rawJson: 'Raw JSON override',
  add: 'Add', duplicate: 'Duplicate', delete: 'Delete', moveUp: 'Move up', moveDown: 'Move down', done: 'Done', notEveryCollection: 'Not available in every collection',
  edit: 'Edit', remove: 'Remove', reset: 'Reset', cancel: 'Cancel', continue: 'Continue', import: 'Import', use: 'Use', useAgain: 'Use again', reorder: 'Reorder', saveSchema: 'Save schema', addSchema: 'Add schema', editSchema: 'Edit schema', editValues: 'Edit values', resetOverrides: 'Reset overrides', overrideValue: 'Override', inherited: 'Inherited', customized: 'Customized', 'default': 'Default', copySuffix: 'copy',
  globalSchemas: 'Global schemas', globalSchemasDescription: 'Automatically applied to every enabled document.', collectionSchemas: 'Collection schemas', enabledCollection: 'Enabled collection', globalScope: 'Global', noGlobalSchemas: 'No global schemas yet.', noCollectionSchemas: 'No schemas for this collection yet.', confirmDeleteSchema: 'Delete this schema? Referenced templates will still be protected by the server.', confirmDeleteProperty: 'Delete this property or item and everything nested inside it?',
  chooseStarter: 'Choose a starting point', chooseStarterDescription: 'Pick a ready-made schema, start from scratch, or import JSON.', startScratch: 'Start from scratch', startScratchDescription: 'Begin with an empty schema object.', importJson: 'Import JSON', importJsonDescription: 'Paste one JSON object. HTML script tags are not supported.', importedSchema: 'Imported schema', untitledSchema: 'Untitled schema', backToStarters: 'Back to schema types', importContextExplanation: 'The @context key is managed by the plugin and cannot be stored in a template.', removeAndContinue: 'Remove and continue',
  schemaName: 'Schema name', defaultSchema: 'Use by default', schemaRoot: 'Schema root', breadcrumb: 'Schema breadcrumb', propertyName: 'Property name', valueType: 'Value type', addProperty: 'Add property', addItem: 'Add item', emptyObject: 'This object has no properties.', emptyArray: 'This array has no items.', propertiesCount: '{count} properties', itemsCount: '{count} items', string: 'String', number: 'Number', boolean: 'Boolean', 'null': 'Null', object: 'Object', array: 'Array', 'true': 'True', 'false': 'False', structureInherited: 'Schema structure is inherited. Scalar values can still be overridden.', localizedEditingNotice: 'This locale inherits the schema structure. Use Override or Reset to manage localized scalar values.', localizedStructureError: 'Structure cannot be changed outside the default locale.',
  showRawJson: 'Show raw JSON', rawApplyDescription: 'Changes stay isolated until Apply JSON. Invalid JSON will not change the visual editor.', applyJson: 'Apply JSON',
  documentSchemas: 'Document schemas', documentSchemasDescription: 'Custom schemas stored only on this document.', createDocumentSchema: 'Create custom schema', documentScope: 'This document', noDocumentSchemas: 'No custom document schemas yet.', appliedGlobally: 'Applied globally', appliedGloballyDescription: 'These schemas are required by Settings and cannot be removed here.', globalLocked: 'Global schemas cannot be removed from a document.', schemaInUse: 'Schema in use', schemaInUseDescription: 'Collection templates selected for this document.', noSchemasInUse: 'No collection schemas are in use.', chooseSchema: 'Choose schema', availableSchemas: 'Available schemas', availableSchemasDescription: 'A template may be used more than once.', missingTemplate: 'Missing template', missingTemplateDescription: 'This reference no longer has an available template.', loadingSchemas: 'Loading schemas…', schemaLoadFailed: 'Schemas could not be loaded.', schemaAccessDenied: 'You do not have access to these schema templates.',
  name: 'Name', about: 'About', headline: 'Headline', author: 'Author', datePublished: 'Published date', dateModified: 'Modified date', productDescription: 'Product description', sku: 'SKU', brand: 'Brand', price: 'Price', priceCurrency: 'Price currency', telephone: 'Telephone', address: 'Address', question: 'Question', answer: 'Answer',
  seoSettings: 'SEO settings', siteDefaults: 'Site defaults', siteName: 'Site name', titleTemplate: 'Title template', defaultDescription: 'Default description', socialDefaults: 'Social defaults', defaultOpenGraphImage: 'Default Open Graph image', defaultOpenGraphType: 'Default Open Graph type', defaultTwitterCard: 'Default X / Twitter card', defaultTwitterSite: 'Default X / Twitter site', defaultTwitterCreator: 'Default X / Twitter creator', defaultLocale: 'Default locale', defaultRobots: 'Default robots', organizationSchema: 'Organization schema', organizationName: 'Organization name', organizationUrl: 'Organization URL', organizationLogo: 'Organization logo', robotsTxt: 'robots.txt', robotsMode: 'Robots mode', directives: 'Directives', generated: 'Generated', override: 'Override', groups: 'Groups', userAgent: 'User-agent', allow: 'Allow', disallow: 'Disallow', path: 'Path', appendText: 'Append text', overrideText: 'Override text',
  seoRedirect: 'SEO redirect', seoRedirects: 'SEO redirects', source: 'Source', destinationType: 'Destination type', destination: 'Destination', internal: 'Internal', external: 'External', statusCode: 'Status code', permanentRedirect: '301 Permanent', temporaryRedirect: '302 Temporary', enabled: 'Enabled', notes: 'Notes',
  validationAbsoluteHttpUrl: 'Enter an absolute HTTP or HTTPS URL.', validationJson: 'Enter valid JSON.', validationManualCanonical: 'A manual canonical URL is required.', validationInternalPath: 'Enter an internal path beginning with one slash, without an origin, query string, or fragment.', validationRedirectLoop: 'Redirects cannot form a loop.',
  validationSchemaRoot: 'Schema JSON must have an object at its root.', validationSchemaContext: 'The @context key is managed by the plugin.', validationSchemaPatch: 'Enter valid add, replace, or remove schema overrides.',
  previewAriaLabel: 'SEO previews', previewTitle: 'Page title', previewDescription: 'Add a concise description to preview how this document may appear when shared.', previewImageMissing: 'No image selected', googleResult: 'Google result', openGraphPreview: 'Open Graph · example.com', twitterPreview: 'X card · example.com',
  generatedJson: 'Generated JSON', copy: 'Copy', copied: 'Copied', generatedJsonDescription: 'This reflects the visual schema fields. A raw override takes precedence when saved.', useGeneratedJson: 'Use generated JSON as override', rawJsonDescription: 'Optional. Valid JSON here replaces the generated schema entirely.', clearRawJson: 'Clear raw JSON override',
  schemaOverridesDescription: 'Values configured by your developer are inherited from this document. Leave a field empty to use its mapped value.', schemaOverrideValue: 'Using {path}: {value}. Enter a value only to override it.', yes: 'Yes', no: 'No',
} as const

export type SeoTranslation = {
  [Key in keyof typeof en]: string
}
