import type { Access, Field, FieldAccess, PayloadRequest } from 'payload'

/** Metadata marker written to every Payload entity generated by this plugin. */
export const SEO_PLUGIN_MARKER = '@krameri/payload-seo'

export const DEFAULT_SEO_NAMES = {
  redirectsCollection: 'seo-redirects',
  seoField: 'seo',
  settingsGlobal: 'seo-settings',
} as const

export type SeoSchemaType =
  | 'Article'
  | 'FAQPage'
  | 'LocalBusiness'
  | 'Organization'
  | 'Product'
  | 'WebPage'

export type SeoDocument = Record<string, unknown>

export type ResolveDocumentUrl = (input: {
  collection: string
  document: SeoDocument
  locale: string
}) => null | Promise<null | string> | string

export type ResolveLastModified = (input: {
  collection: string
  document: SeoDocument
  locale: string
}) => Date | null | Promise<Date | null | string> | string

export type ResolveMediaUrl = (input: {
  locale: string
  media: SeoDocument
}) => null | Promise<null | string> | string

export type ResolveSitemapChunkUrl = (input: {
  collection: string
  locale: string
  page: number
}) => Promise<string> | string

export type ResolveRobotsSitemapUrls = (input: {
  locale: string
}) => Promise<readonly string[]> | readonly string[]

export type SeoDocumentFieldMappings = {
  description?: string
  image?: string
  title?: string
}

export type SeoSitemapConfig = {
  enabled?: boolean
}

export type SeoCollectionConfig = {
  fields?: SeoDocumentFieldMappings
  lastModified?: ResolveLastModified
  media?: {
    collection: string
  }
  schema?: Record<string, string>
  schemaType: SeoSchemaType
  sitemap?: SeoSitemapConfig
  /** Additional schema-editor fields. Their Payload field validation is added in Milestone 2. */
  visualFields?: Field[]
  /** Additive boolean field access for the generated SEO group. */
  access?: {
    read?: FieldAccess
    update?: FieldAccess
  }
}

export type SeoPluginAccess = {
  redirects?: {
    admin?: ({ req }: { req: PayloadRequest }) => boolean | Promise<boolean>
    create?: Access
    delete?: Access
    read?: Access
    update?: Access
  }
  settings?: {
    read?: Access
    update?: Access
  }
}

export type SeoGeneratedNames = {
  redirectsCollection?: string
  seoField?: string
  settingsGlobal?: string
}

export type SeoEnabledPluginConfig = {
  collections: Record<string, SeoCollectionConfig>
  enabled?: true
  media: {
    collection: string
    resolveMediaUrl: ResolveMediaUrl
  }
  resolveChunkUrl: ResolveSitemapChunkUrl
  resolveUrl: ResolveDocumentUrl
  access?: SeoPluginAccess
  names?: SeoGeneratedNames
  robots?: {
    resolveSitemapUrls?: ResolveRobotsSitemapUrls
  }
}

/** Disabled mode deliberately accepts no active-plugin requirements. */
export type SeoDisabledPluginConfig = {
  enabled: false
} & Partial<Omit<SeoEnabledPluginConfig, 'enabled'>>

export type SeoPluginConfig = SeoDisabledPluginConfig | SeoEnabledPluginConfig

/** Shape stored in `admin.custom` on generated fields, globals, and collections. */
export type SeoAdminCustom = {
  seo?: {
    marker: typeof SEO_PLUGIN_MARKER
  }
}
