import type { Access, Field, FieldAccess, PayloadRequest } from 'payload'

/** Metadata marker written to every Payload entity generated by this plugin. */
export const SEO_PLUGIN_MARKER = '@krameri/payload-seo'

export const DEFAULT_SEO_NAMES = {
  redirectsCollection: 'seo-redirects',
  seoField: 'seo',
  settingsGlobal: 'seo-settings',
} as const

/** Client component paths registered on generated Payload Admin fields. */
export const SEO_PREVIEWS_ADMIN_COMPONENT =
  '@krameri/payload-seo/client#SeoPreviews'
export const SEO_RAW_JSON_ADMIN_COMPONENT =
  '@krameri/payload-seo/client#ResetRawJson'
export const SEO_SCHEMA_VALUE_OVERRIDES_ADMIN_COMPONENT =
  '@krameri/payload-seo/client#SchemaValueOverrides'

export type SeoSchemaType =
  | 'Article'
  | 'FAQPage'
  | 'LocalBusiness'
  | 'Organization'
  | 'Product'
  | 'WebPage'

export type SeoDocument = Record<string, unknown>

export type RobotsMode =
  | 'inherit'
  | 'index-follow'
  | 'noindex-follow'
  | 'index-nofollow'
  | 'noindex-nofollow'
  | 'custom'

export type CanonicalMode = 'auto' | 'manual' | 'none'
export type TrailingSlashPolicy = 'always' | 'never'

export type ResolveDocumentUrl = (input: {
  collection: string
  document: SeoDocument
  locale: string
}) => null | Promise<null | string> | string

export type ResolveLastModified = (input: {
  collection: string
  document: SeoDocument
  locale: string
}) => Date | null | Promise<Date | null | string> | string

export type ResolveMediaUrl = (input: {
  locale: string
  media: SeoDocument
}) => null | Promise<null | string> | string

export type ResolveSitemapChunkUrl = (input: {
  collection: string
  locale: string
  page: number
}) => Promise<string> | string

export type ResolveRobotsSitemapUrls = (input: {
  locale: string
}) => Promise<readonly string[]> | readonly string[]

export type SeoDocumentFieldMappings = {
  description?: string
  image?: string
  title?: string
}

export type SeoBreadcrumbItem = {
  name: string
  /** Absolute HTTP(S) URL, or a site-relative path resolved against `siteUrl`. */
  url: string
}

export type ResolveBreadcrumbs = (input: {
  collection: string
  document: SeoDocument
  locale: string
  canonicalUrl?: string
}) => readonly SeoBreadcrumbItem[] | Promise<readonly SeoBreadcrumbItem[]>

export type SeoSitemapConfig = {
  enabled?: boolean
  /**
   * Document paths required by `resolveUrl`, `lastModified`, and `exclude`
   * while rendering a sitemap page. Supplying them keeps large sitemap reads
   * projected; the callback receives exactly this projection plus SEO state.
   */
  fields?: readonly string[]
  /** Return false to omit a document after its effective SEO state is resolved. */
  exclude?: (input: {
    collection: string
    document: SeoDocument
    locale: string
    /** Sitemap resolution deliberately computes only canonical and robots state. */
    effective: ResolvedSitemapSeo
  }) => boolean | Promise<boolean>
}

export type SeoCollectionConfig = {
  fields?: SeoDocumentFieldMappings
  lastModified?: ResolveLastModified
  media?: {
    collection: string
  }
  /** Optional host-owned breadcrumb resolver. Invalid items are omitted. */
  breadcrumbs?: ResolveBreadcrumbs
  schema?: Record<string, string>
  schemaType: SeoSchemaType
  sitemap?: SeoSitemapConfig
  /** Additional schema-editor fields displayed alongside the built-in type-specific fields. */
  visualFields?: Field[]
  /** Additive boolean field access for the generated SEO group. */
  access?: {
    read?: FieldAccess
    update?: FieldAccess
  }
}

export type SeoPluginAccess = {
  redirects?: {
    admin?: ({ req }: { req: PayloadRequest }) => boolean | Promise<boolean>
    create?: Access
    delete?: Access
    read?: Access
    update?: Access
  }
  settings?: {
    read?: Access
    update?: Access
  }
}

export type SeoGeneratedNames = {
  redirectsCollection?: string
  seoField?: string
  settingsGlobal?: string
}

export type SeoEnabledPluginConfig = {
  collections: Record<string, SeoCollectionConfig>
  enabled?: true
  /** Immutable public site origin, normally supplied from the host environment. */
  siteUrl: string
  media: {
    collection: string
    resolveMediaUrl: ResolveMediaUrl
  }
  resolveChunkUrl: ResolveSitemapChunkUrl
  resolveUrl: ResolveDocumentUrl
  /** URL policy used consistently by canonicals, alternates, and sitemaps. */
  url?: { trailingSlash?: TrailingSlashPolicy }
  hreflang?: { xDefaultLocale?: string }
  /** Receives resolution failures without document values or other sensitive input. */
  diagnostics?: (event: SeoDiagnostic) => void
  access?: SeoPluginAccess
  names?: SeoGeneratedNames
  robots?: {
    resolveSitemapUrls?: ResolveRobotsSitemapUrls
  }
}

/** Disabled mode deliberately accepts no active-plugin requirements. */
export type SeoDisabledPluginConfig = {
  enabled: false
} & Partial<Omit<SeoEnabledPluginConfig, 'enabled'>>

export type SeoPluginConfig = SeoDisabledPluginConfig | SeoEnabledPluginConfig

/** Shape stored in `admin.custom` on generated fields, globals, and collections. */
export type SeoAdminCustom = {
  seo?: {
    marker: typeof SEO_PLUGIN_MARKER
  }
}

/** Locale-explicit subset of the Payload Local API used by the resolver core. */
export type SeoPayload = {
  findByID: (options: Record<string, unknown>) => Promise<SeoDocument>
  findGlobal: (options: Record<string, unknown>) => Promise<SeoDocument>
  find?: (options: Record<string, unknown>) => Promise<{ docs: SeoDocument[]; totalDocs?: number }>
  config?: {
    custom?: Record<string, unknown>
    localization?: { locales?: Array<string | { code?: string }> }
  }
}

/** Optional context passed to Payload Local API reads performed for an Admin preview. */
export type SeoLocalApiOptions = {
  overrideAccess: false
  req?: PayloadRequest
  user?: unknown
}

export type SeoRobotsDirectives = {
  /** Normalized supported directives selected in custom mode (including explicit index/follow tokens). */
  custom?: string[]
  follow?: 'follow' | 'nofollow'
  index?: 'index' | 'noindex'
}

export type SeoDiagnostic = {
  area: 'canonical' | 'media' | 'metadata' | 'robots' | 'schema' | 'sitemap' | 'url'
  collection?: string
  documentId?: string | number
  locale?: string
  message: string
}

export type SeoSocialMetadata = {
  description?: string
  image?: string
  title?: string
}

export type ResolvedEffectiveSeo = {
  title?: string
  description?: string
  canonical: { mode: CanonicalMode; url?: string; external: boolean }
  robots: { index: 'index' | 'noindex'; follow: 'follow' | 'nofollow'; mode: RobotsMode; custom?: string[] }
  social: {
    openGraph: SeoSocialMetadata & { url?: string; type?: string; siteName?: string; locale?: string }
    twitter: SeoSocialMetadata & { card?: 'summary' | 'summary_large_image'; site?: string; creator?: string }
  }
  schema?: Record<string, unknown>
  siteSchemas: Record<string, unknown>[]
  breadcrumbs: Record<string, unknown>[]
}

export type ResolvedSitemapSeo = Pick<ResolvedEffectiveSeo, 'canonical' | 'robots'>

export type SeoPreview = {
  canonicalUrl?: string
  description?: string
  image?: string
  openGraph?: SeoSocialMetadata
  robots: { index: 'index' | 'noindex'; follow: 'follow' | 'nofollow'; custom?: string[] }
  title?: string
  twitter?: SeoSocialMetadata & { card?: 'summary' | 'summary_large_image'; site?: string; creator?: string }
  /** The exact resolved schema payload returned by the public schema helper. */
  schema?: Record<string, unknown>
}

/** Framework-neutral, omission-first output of the locale-safe resolver. */
export type ResolvedSeoMetadata = {
  alternates?: Record<string, string>
  canonicalUrl?: string
  description?: string
  openGraph?: SeoSocialMetadata & { url?: string; type?: string; siteName?: string; locale?: string }
  robots?: SeoRobotsDirectives
  schema?: Record<string, unknown>
  title?: string
  twitter?: SeoSocialMetadata & { card?: 'summary' | 'summary_large_image'; site?: string; creator?: string }
}
