import type { LabelFunction } from 'payload'

const en = {
  contentTab: 'Content', seoTab: 'SEO', seo: 'SEO', general: 'General', canonical: 'Canonical', robots: 'Robots', openGraph: 'Open Graph', twitter: 'X / Twitter', schema: 'Schema', previews: 'Previews',
  title: 'Title', description: 'Description', focusKeyword: 'Keywords', defaultKeywords: 'Default keywords', keywordsDescription: 'Separate keywords with ",".', image: 'Image', card: 'Card',
  canonicalMode: 'Canonical mode', canonicalUrl: 'Canonical URL', auto: 'Auto', manual: 'Manual', none: 'None',
  robotsIndex: 'Index directive', robotsFollow: 'Follow directive', index: 'Index', noindex: 'No index', follow: 'Follow', nofollow: 'No follow',
  summary: 'Summary', summaryLargeImage: 'Summary large image',
  schemaType: 'Schema type', schemaOverrides: 'Schema overrides', rawJson: 'Raw JSON override',
  add: 'Add', duplicate: 'Duplicate', delete: 'Delete', moveUp: 'Move up', moveDown: 'Move down', done: 'Done', notEveryCollection: 'Not available in every collection',
  edit: 'Edit', remove: 'Remove', reset: 'Reset', cancel: 'Cancel', continue: 'Continue', import: 'Import', use: 'Use', useAgain: 'Use again', reorder: 'Reorder', saveSchema: 'Save schema', addSchema: 'Add schema', editSchema: 'Edit schema', editValues: 'Edit values', resetOverrides: 'Reset overrides', overrideValue: 'Override', inherited: 'Inherited', customized: 'Customized', 'default': 'Default', copySuffix: 'copy',
  globalSchemas: 'Global schemas', globalSchemasDescription: 'Automatically applied to every enabled document.', collectionSchemas: 'Collection schemas', enabledCollection: 'Enabled collection', globalScope: 'Global', noGlobalSchemas: 'No global schemas yet.', noCollectionSchemas: 'No schemas for this collection yet.', confirmDeleteSchema: 'Delete this schema? Referenced templates will still be protected by the server.', confirmDeleteProperty: 'Delete this property or item and everything nested inside it?',
  chooseStarter: 'Choose a starting point', chooseStarterDescription: 'Pick a ready-made schema, start from scratch, or import JSON.', startScratch: 'Start from scratch', startScratchDescription: 'Begin with an empty schema object.', importJson: 'Import JSON', importJsonDescription: 'Paste one JSON object. HTML script tags are not supported.', importedSchema: 'Imported schema', untitledSchema: 'Untitled schema', backToStarters: 'Back to schema types', importContextExplanation: 'The @context key is managed by the plugin and cannot be stored in a template.', removeAndContinue: 'Remove and continue',
  schemaName: 'Schema name', defaultSchema: 'Use by default', schemaRoot: 'Schema root', breadcrumb: 'Schema breadcrumb', propertyName: 'Property name', valueType: 'Value type', addProperty: 'Add property', addItem: 'Add item', emptyObject: 'This object has no properties.', emptyArray: 'This array has no items.', propertiesCount: '{count} properties', itemsCount: '{count} items', string: 'String', number: 'Number', boolean: 'Boolean', 'null': 'Null', object: 'Object', array: 'Array', 'true': 'True', 'false': 'False', structureInherited: 'Schema structure is inherited. Scalar values can still be overridden.', localizedEditingNotice: 'This locale inherits the schema structure. Use Override or Reset to manage localized scalar values.', localizedStructureError: 'Structure cannot be changed outside the default locale.',
  showRawJson: 'Show raw JSON', rawApplyDescription: 'Changes stay isolated until Apply JSON. Invalid JSON will not change the visual editor.', applyJson: 'Apply JSON',
  documentSchemas: 'Document schemas', documentSchemasDescription: 'Custom schemas stored only on this document.', createDocumentSchema: 'Create custom schema', documentScope: 'This document', noDocumentSchemas: 'No custom document schemas yet.', appliedGlobally: 'Applied globally', appliedGloballyDescription: 'These schemas are required by Settings and cannot be removed here.', globalLocked: 'Global schemas cannot be removed from a document.', schemaInUse: 'Schema in use', schemaInUseDescription: 'Collection templates selected for this document.', noSchemasInUse: 'No collection schemas are in use.', chooseSchema: 'Choose schema', availableSchemas: 'Available schemas', availableSchemasDescription: 'A template may be used more than once.', missingTemplate: 'Missing template', missingTemplateDescription: 'This reference no longer has an available template.', loadingSchemas: 'Loading schemas…', schemaLoadFailed: 'Schemas could not be loaded.', schemaAccessDenied: 'You do not have access to these schema templates.',
  name: 'Name', about: 'About', headline: 'Headline', author: 'Author', datePublished: 'Published date', dateModified: 'Modified date', productDescription: 'Product description', sku: 'SKU', brand: 'Brand', price: 'Price', priceCurrency: 'Price currency', telephone: 'Telephone', address: 'Address', question: 'Question', answer: 'Answer',
  seoSettings: 'SEO settings', siteDefaults: 'Site defaults', siteName: 'Site name', titleTemplate: 'Title template', defaultDescription: 'Default description', socialDefaults: 'Social defaults', defaultOpenGraphImage: 'Default Open Graph image', defaultTwitterCard: 'Default X / Twitter card', defaultRobots: 'Default robots', organizationSchema: 'Organization schema', organizationName: 'Organization name', organizationUrl: 'Organization URL', organizationLogo: 'Organization logo', robotsTxt: 'robots.txt', robotsMode: 'Robots mode', generated: 'Generated', override: 'Override', groups: 'Groups', userAgent: 'User-agent', allow: 'Allow', disallow: 'Disallow', path: 'Path', appendText: 'Append text', overrideText: 'Override text',
  seoRedirect: 'SEO redirect', seoRedirects: 'SEO redirects', source: 'Source', destinationType: 'Destination type', destination: 'Destination', internal: 'Internal', external: 'External', statusCode: 'Status code', permanentRedirect: '301 Permanent', temporaryRedirect: '302 Temporary', enabled: 'Enabled', notes: 'Notes',
  validationAbsoluteHttpUrl: 'Enter an absolute HTTP or HTTPS URL.', validationJson: 'Enter valid JSON.', validationManualCanonical: 'A manual canonical URL is required.', validationInternalPath: 'Enter an internal path beginning with one slash, without an origin, query string, or fragment.', validationRedirectLoop: 'Redirects cannot form a loop.',
  validationSchemaRoot: 'Schema JSON must have an object at its root.', validationSchemaContext: 'The @context key is managed by the plugin.', validationSchemaPatch: 'Enter valid add, replace, or remove schema overrides.',
  previewAriaLabel: 'SEO previews', previewTitle: 'Page title', previewDescription: 'Add a concise description to preview how this document may appear when shared.', previewImageMissing: 'No image selected', googleResult: 'Google result', openGraphPreview: 'Open Graph · example.com', twitterPreview: 'X card · example.com',
  generatedJson: 'Generated JSON', copy: 'Copy', copied: 'Copied', generatedJsonDescription: 'This reflects the visual schema fields. A raw override takes precedence when saved.', useGeneratedJson: 'Use generated JSON as override', rawJsonDescription: 'Optional. Valid JSON here replaces the generated schema entirely.', clearRawJson: 'Clear raw JSON override',
  schemaOverridesDescription: 'Values configured by your developer are inherited from this document. Leave a field empty to use its mapped value.', schemaOverrideValue: 'Using {path}: {value}. Enter a value only to override it.', yes: 'Yes', no: 'No',
} as const

type AdminText = { [Key in keyof typeof en]: string }

const ru: AdminText = {
  contentTab: 'Содержимое', seoTab: 'SEO', seo: 'SEO', general: 'Основное', canonical: 'Канонический URL', robots: 'Robots', openGraph: 'Open Graph', twitter: 'X / Twitter', schema: 'Schema', previews: 'Предпросмотр',
  title: 'Заголовок', description: 'Описание', focusKeyword: 'Ключевые слова', defaultKeywords: 'Ключевые слова по умолчанию', keywordsDescription: 'Разделяйте ключевые слова символом ",".', image: 'Изображение', card: 'Карточка',
  canonicalMode: 'Режим канонического URL', canonicalUrl: 'Канонический URL', auto: 'Автоматически', manual: 'Вручную', none: 'Нет',
  robotsIndex: 'Директива индексации', robotsFollow: 'Директива ссылок', index: 'Индексировать', noindex: 'Не индексировать', follow: 'Переходить по ссылкам', nofollow: 'Не переходить по ссылкам',
  summary: 'Краткая', summaryLargeImage: 'Краткая с большим изображением',
  schemaType: 'Тип Schema', schemaOverrides: 'Переопределения Schema', rawJson: 'Переопределение Raw JSON',
  add: 'Добавить', duplicate: 'Дублировать', delete: 'Удалить', moveUp: 'Переместить вверх', moveDown: 'Переместить вниз', done: 'Готово', notEveryCollection: 'Доступно не во всех коллекциях',
  edit: 'Изменить', remove: 'Удалить', reset: 'Сбросить', cancel: 'Отмена', continue: 'Продолжить', import: 'Импортировать', use: 'Использовать', useAgain: 'Использовать снова', reorder: 'Изменить порядок', saveSchema: 'Сохранить Schema', addSchema: 'Добавить Schema', editSchema: 'Редактировать Schema', editValues: 'Изменить значения', resetOverrides: 'Сбросить переопределения', overrideValue: 'Переопределить', inherited: 'Унаследовано', customized: 'Настроено', 'default': 'По умолчанию', copySuffix: 'копия',
  globalSchemas: 'Глобальные Schema', globalSchemasDescription: 'Автоматически применяются ко всем включённым документам.', collectionSchemas: 'Schema коллекций', enabledCollection: 'Включённая коллекция', globalScope: 'Глобальная', noGlobalSchemas: 'Глобальных Schema пока нет.', noCollectionSchemas: 'Для этой коллекции Schema пока нет.', confirmDeleteSchema: 'Удалить эту Schema? Сервер всё равно защитит шаблоны, на которые есть ссылки.', confirmDeleteProperty: 'Удалить это свойство или элемент и всё вложенное содержимое?',
  chooseStarter: 'Выберите основу', chooseStarterDescription: 'Выберите готовую Schema, начните с нуля или импортируйте JSON.', startScratch: 'Начать с нуля', startScratchDescription: 'Начать с пустого объекта Schema.', importJson: 'Импорт JSON', importJsonDescription: 'Вставьте один объект JSON. HTML-теги script не поддерживаются.', importedSchema: 'Импортированная Schema', untitledSchema: 'Schema без названия', backToStarters: 'Назад к типам Schema', importContextExplanation: 'Ключ @context управляется плагином и не может храниться в шаблоне.', removeAndContinue: 'Удалить и продолжить',
  schemaName: 'Название Schema', defaultSchema: 'Использовать по умолчанию', schemaRoot: 'Корень Schema', breadcrumb: 'Путь Schema', propertyName: 'Имя свойства', valueType: 'Тип значения', addProperty: 'Добавить свойство', addItem: 'Добавить элемент', emptyObject: 'В этом объекте нет свойств.', emptyArray: 'В этом массиве нет элементов.', propertiesCount: 'Свойств: {count}', itemsCount: 'Элементов: {count}', string: 'Строка', number: 'Число', boolean: 'Логическое', 'null': 'Null', object: 'Объект', array: 'Массив', 'true': 'Да', 'false': 'Нет', structureInherited: 'Структура Schema унаследована. Скалярные значения можно переопределять.', localizedEditingNotice: 'Эта локаль наследует структуру Schema. Используйте «Переопределить» или «Сбросить» для локализованных значений.', localizedStructureError: 'Структуру можно менять только в локали по умолчанию.',
  showRawJson: 'Показать raw JSON', rawApplyDescription: 'Изменения изолированы до нажатия «Применить JSON». Ошибка JSON не изменит визуальный редактор.', applyJson: 'Применить JSON',
  documentSchemas: 'Schema документа', documentSchemasDescription: 'Пользовательские Schema, сохранённые только в этом документе.', createDocumentSchema: 'Создать пользовательскую Schema', documentScope: 'Этот документ', noDocumentSchemas: 'Пользовательских Schema документа пока нет.', appliedGlobally: 'Применяются глобально', appliedGloballyDescription: 'Эти Schema обязательны в настройках и не могут быть удалены здесь.', globalLocked: 'Глобальные Schema нельзя удалить из документа.', schemaInUse: 'Используемые Schema', schemaInUseDescription: 'Шаблоны коллекции, выбранные для этого документа.', noSchemasInUse: 'Schema коллекции не используются.', chooseSchema: 'Выбрать Schema', availableSchemas: 'Доступные Schema', availableSchemasDescription: 'Один шаблон можно использовать несколько раз.', missingTemplate: 'Шаблон отсутствует', missingTemplateDescription: 'Для этой ссылки больше нет доступного шаблона.', loadingSchemas: 'Загрузка Schema…', schemaLoadFailed: 'Не удалось загрузить Schema.', schemaAccessDenied: 'У вас нет доступа к этим шаблонам Schema.',
  name: 'Название', about: 'О странице', headline: 'Заголовок', author: 'Автор', datePublished: 'Дата публикации', dateModified: 'Дата изменения', productDescription: 'Описание товара', sku: 'Артикул', brand: 'Бренд', price: 'Цена', priceCurrency: 'Валюта цены', telephone: 'Телефон', address: 'Адрес', question: 'Вопрос', answer: 'Ответ',
  seoSettings: 'Настройки SEO', siteDefaults: 'Настройки сайта', siteName: 'Название сайта', titleTemplate: 'Шаблон заголовка', defaultDescription: 'Описание по умолчанию', socialDefaults: 'Настройки соцсетей', defaultOpenGraphImage: 'Изображение Open Graph по умолчанию', defaultTwitterCard: 'Карточка X / Twitter по умолчанию', defaultRobots: 'Robots по умолчанию', organizationSchema: 'Schema организации', organizationName: 'Название организации', organizationUrl: 'URL организации', organizationLogo: 'Логотип организации', robotsTxt: 'robots.txt', robotsMode: 'Режим robots', generated: 'Сгенерированный', override: 'Переопределение', groups: 'Группы', userAgent: 'User-agent', allow: 'Разрешить', disallow: 'Запретить', path: 'Путь', appendText: 'Добавить текст', overrideText: 'Текст переопределения',
  seoRedirect: 'SEO-перенаправление', seoRedirects: 'SEO-перенаправления', source: 'Источник', destinationType: 'Тип назначения', destination: 'Назначение', internal: 'Внутреннее', external: 'Внешнее', statusCode: 'Код статуса', permanentRedirect: '301 Постоянное', temporaryRedirect: '302 Временное', enabled: 'Включено', notes: 'Заметки',
  validationAbsoluteHttpUrl: 'Введите абсолютный URL HTTP или HTTPS.', validationJson: 'Введите корректный JSON.', validationManualCanonical: 'Требуется канонический URL, заданный вручную.', validationInternalPath: 'Введите внутренний путь, начинающийся с одного слеша, без домена, строки запроса или фрагмента.', validationRedirectLoop: 'Перенаправления не могут образовывать цикл.',
  validationSchemaRoot: 'Корнем JSON Schema должен быть объект.', validationSchemaContext: 'Ключ @context управляется плагином.', validationSchemaPatch: 'Введите корректные переопределения Schema add, replace или remove.',
  previewAriaLabel: 'Предпросмотры SEO', previewTitle: 'Заголовок страницы', previewDescription: 'Добавьте краткое описание, чтобы увидеть, как документ может выглядеть при публикации.', previewImageMissing: 'Изображение не выбрано', googleResult: 'Результат Google', openGraphPreview: 'Open Graph · example.com', twitterPreview: 'Карточка X · example.com',
  generatedJson: 'Сгенерированный JSON', copy: 'Копировать', copied: 'Скопировано', generatedJsonDescription: 'Это отражает визуальные поля Schema. При сохранении Raw JSON имеет приоритет.', useGeneratedJson: 'Использовать сгенерированный JSON как переопределение', rawJsonDescription: 'Необязательно. Корректный JSON здесь полностью заменяет сгенерированную Schema.', clearRawJson: 'Очистить переопределение Raw JSON',
  schemaOverridesDescription: 'Значения, настроенные разработчиком, наследуются из этого документа. Оставьте поле пустым, чтобы использовать сопоставленное значение.', schemaOverrideValue: 'Используется {path}: {value}. Введите значение, только чтобы переопределить его.', yes: 'Да', no: 'Нет',
}

const uk: AdminText = {
  contentTab: 'Вміст', seoTab: 'SEO', seo: 'SEO', general: 'Загальне', canonical: 'Канонічний URL', robots: 'Robots', openGraph: 'Open Graph', twitter: 'X / Twitter', schema: 'Schema', previews: 'Попередній перегляд',
  title: 'Заголовок', description: 'Опис', focusKeyword: 'Ключові слова', defaultKeywords: 'Ключові слова за замовчуванням', keywordsDescription: 'Розділяйте ключові слова символом ",".', image: 'Зображення', card: 'Картка',
  canonicalMode: 'Режим канонічного URL', canonicalUrl: 'Канонічний URL', auto: 'Автоматично', manual: 'Вручну', none: 'Немає',
  robotsIndex: 'Директива індексації', robotsFollow: 'Директива посилань', index: 'Індексувати', noindex: 'Не індексувати', follow: 'Переходити за посиланнями', nofollow: 'Не переходити за посиланнями',
  summary: 'Коротка', summaryLargeImage: 'Коротка з великим зображенням',
  schemaType: 'Тип Schema', schemaOverrides: 'Перевизначення Schema', rawJson: 'Перевизначення Raw JSON',
  add: 'Додати', duplicate: 'Дублювати', delete: 'Видалити', moveUp: 'Перемістити вгору', moveDown: 'Перемістити вниз', done: 'Готово', notEveryCollection: 'Доступно не в усіх колекціях',
  edit: 'Редагувати', remove: 'Вилучити', reset: 'Скинути', cancel: 'Скасувати', continue: 'Продовжити', import: 'Імпортувати', use: 'Використати', useAgain: 'Використати знову', reorder: 'Змінити порядок', saveSchema: 'Зберегти Schema', addSchema: 'Додати Schema', editSchema: 'Редагувати Schema', editValues: 'Редагувати значення', resetOverrides: 'Скинути перевизначення', overrideValue: 'Перевизначити', inherited: 'Успадковано', customized: 'Налаштовано', 'default': 'За замовчуванням', copySuffix: 'копія',
  globalSchemas: 'Глобальні Schema', globalSchemasDescription: 'Автоматично застосовуються до всіх увімкнених документів.', collectionSchemas: 'Schema колекцій', enabledCollection: 'Увімкнена колекція', globalScope: 'Глобальна', noGlobalSchemas: 'Глобальних Schema ще немає.', noCollectionSchemas: 'Для цієї колекції Schema ще немає.', confirmDeleteSchema: 'Видалити цю Schema? Сервер усе одно захистить шаблони, на які є посилання.', confirmDeleteProperty: 'Видалити цю властивість або елемент і весь вкладений вміст?',
  chooseStarter: 'Оберіть основу', chooseStarterDescription: 'Оберіть готову Schema, почніть з нуля або імпортуйте JSON.', startScratch: 'Почати з нуля', startScratchDescription: 'Почати з порожнього об’єкта Schema.', importJson: 'Імпорт JSON', importJsonDescription: 'Вставте один об’єкт JSON. HTML-теги script не підтримуються.', importedSchema: 'Імпортована Schema', untitledSchema: 'Schema без назви', backToStarters: 'Назад до типів Schema', importContextExplanation: 'Ключ @context керується плагіном і не може зберігатися в шаблоні.', removeAndContinue: 'Видалити й продовжити',
  schemaName: 'Назва Schema', defaultSchema: 'Використовувати за замовчуванням', schemaRoot: 'Корінь Schema', breadcrumb: 'Шлях Schema', propertyName: 'Назва властивості', valueType: 'Тип значення', addProperty: 'Додати властивість', addItem: 'Додати елемент', emptyObject: 'У цьому об’єкті немає властивостей.', emptyArray: 'У цьому масиві немає елементів.', propertiesCount: 'Властивостей: {count}', itemsCount: 'Елементів: {count}', string: 'Рядок', number: 'Число', boolean: 'Логічне', 'null': 'Null', object: 'Об’єкт', array: 'Масив', 'true': 'Так', 'false': 'Ні', structureInherited: 'Структура Schema успадкована. Скалярні значення можна перевизначати.', localizedEditingNotice: 'Ця локаль успадковує структуру Schema. Використовуйте «Перевизначити» або «Скинути» для локалізованих значень.', localizedStructureError: 'Структуру можна змінювати лише в локалі за замовчуванням.',
  showRawJson: 'Показати raw JSON', rawApplyDescription: 'Зміни ізольовані до натискання «Застосувати JSON». Помилка JSON не змінить візуальний редактор.', applyJson: 'Застосувати JSON',
  documentSchemas: 'Schema документа', documentSchemasDescription: 'Власні Schema, збережені лише в цьому документі.', createDocumentSchema: 'Створити власну Schema', documentScope: 'Цей документ', noDocumentSchemas: 'Власних Schema документа ще немає.', appliedGlobally: 'Застосовуються глобально', appliedGloballyDescription: 'Ці Schema обов’язкові в налаштуваннях і не можуть бути вилучені тут.', globalLocked: 'Глобальні Schema не можна вилучити з документа.', schemaInUse: 'Schema у використанні', schemaInUseDescription: 'Шаблони колекції, вибрані для цього документа.', noSchemasInUse: 'Schema колекції не використовуються.', chooseSchema: 'Обрати Schema', availableSchemas: 'Доступні Schema', availableSchemasDescription: 'Один шаблон можна використовувати кілька разів.', missingTemplate: 'Шаблон відсутній', missingTemplateDescription: 'Для цього посилання більше немає доступного шаблону.', loadingSchemas: 'Завантаження Schema…', schemaLoadFailed: 'Не вдалося завантажити Schema.', schemaAccessDenied: 'У вас немає доступу до цих шаблонів Schema.',
  name: 'Назва', about: 'Про сторінку', headline: 'Заголовок', author: 'Автор', datePublished: 'Дата публікації', dateModified: 'Дата зміни', productDescription: 'Опис товару', sku: 'Артикул', brand: 'Бренд', price: 'Ціна', priceCurrency: 'Валюта ціни', telephone: 'Телефон', address: 'Адреса', question: 'Запитання', answer: 'Відповідь',
  seoSettings: 'Налаштування SEO', siteDefaults: 'Налаштування сайту', siteName: 'Назва сайту', titleTemplate: 'Шаблон заголовка', defaultDescription: 'Опис за замовчуванням', socialDefaults: 'Налаштування соцмереж', defaultOpenGraphImage: 'Зображення Open Graph за замовчуванням', defaultTwitterCard: 'Картка X / Twitter за замовчуванням', defaultRobots: 'Robots за замовчуванням', organizationSchema: 'Schema організації', organizationName: 'Назва організації', organizationUrl: 'URL організації', organizationLogo: 'Логотип організації', robotsTxt: 'robots.txt', robotsMode: 'Режим robots', generated: 'Згенерований', override: 'Перевизначення', groups: 'Групи', userAgent: 'User-agent', allow: 'Дозволити', disallow: 'Заборонити', path: 'Шлях', appendText: 'Додати текст', overrideText: 'Текст перевизначення',
  seoRedirect: 'SEO-перенаправлення', seoRedirects: 'SEO-перенаправлення', source: 'Джерело', destinationType: 'Тип призначення', destination: 'Призначення', internal: 'Внутрішнє', external: 'Зовнішнє', statusCode: 'Код статусу', permanentRedirect: '301 Постійне', temporaryRedirect: '302 Тимчасове', enabled: 'Увімкнено', notes: 'Нотатки',
  validationAbsoluteHttpUrl: 'Введіть абсолютний URL HTTP або HTTPS.', validationJson: 'Введіть коректний JSON.', validationManualCanonical: 'Потрібен канонічний URL, заданий вручну.', validationInternalPath: 'Введіть внутрішній шлях, що починається з одного слеша, без домену, рядка запиту або фрагмента.', validationRedirectLoop: 'Перенаправлення не можуть утворювати цикл.',
  validationSchemaRoot: 'Коренем JSON Schema має бути об’єкт.', validationSchemaContext: 'Ключ @context керується плагіном.', validationSchemaPatch: 'Введіть коректні перевизначення Schema add, replace або remove.',
  previewAriaLabel: 'Попередні перегляди SEO', previewTitle: 'Заголовок сторінки', previewDescription: 'Додайте стислий опис, щоб побачити, як документ може виглядати під час поширення.', previewImageMissing: 'Зображення не вибрано', googleResult: 'Результат Google', openGraphPreview: 'Open Graph · example.com', twitterPreview: 'Картка X · example.com',
  generatedJson: 'Згенерований JSON', copy: 'Копіювати', copied: 'Скопійовано', generatedJsonDescription: 'Це відображає візуальні поля Schema. Під час збереження Raw JSON має пріоритет.', useGeneratedJson: 'Використати згенерований JSON як перевизначення', rawJsonDescription: 'Необов’язково. Коректний JSON тут повністю замінює згенеровану Schema.', clearRawJson: 'Очистити перевизначення Raw JSON',
  schemaOverridesDescription: 'Значення, налаштовані розробником, успадковуються з цього документа. Залиште поле порожнім, щоб використати зіставлене значення.', schemaOverrideValue: 'Використовується {path}: {value}. Введіть значення, лише щоб перевизначити його.', yes: 'Так', no: 'Ні',
}

/** The single typed catalog for every plugin-owned Payload Admin string. */
export const adminTranslations = { en, ru, uk } satisfies Record<'en' | 'ru' | 'uk', AdminText>

export type AdminLanguage = keyof typeof adminTranslations
export type AdminTextKey = keyof typeof en

export const resolveAdminLanguage = (language?: string): AdminLanguage => {
  const normalized = language?.trim().toLowerCase().split(/[-_]/, 1)[0]
  return normalized === 'ru' || normalized === 'uk' || normalized === 'en' ? normalized : 'en'
}

export const adminText = (key: AdminTextKey, language?: string, variables: Record<string, string> = {}): string =>
  adminTranslations[resolveAdminLanguage(language)][key].replace(/\{(\w+)\}/g, (_, name: string) => variables[name] ?? `{${name}}`)

/**
 * Payload v3 serializes tab-label callbacks with only `{ t }`, omitting i18n.
 * Keep tab labels as language maps so the Tabs client resolves them itself.
 */
export const adminTabLabel = (key: AdminTextKey): Record<string, string> => ({
  en: adminText(key, 'en'),
  'en-GB': adminText(key, 'en-GB'),
  ru: adminText(key, 'ru'),
  'ru-RU': adminText(key, 'ru-RU'),
  uk: adminText(key, 'uk'),
  'uk-UA': adminText(key, 'uk-UA'),
})

/** Lets Payload resolve generated labels using the active Admin interface language. */
export const adminLabel = (key: AdminTextKey): LabelFunction =>
  ({ i18n }: { i18n?: { language?: string } } = {}) => adminText(key, i18n?.language)
