export type {
  ResolveDocumentUrl,
  ResolveLastModified,
  ResolveMediaUrl,
  ResolveRobotsSitemapUrls,
  ResolveSitemapChunkUrl,
  SeoAdminCustom,
  SeoCollectionConfig,
  SeoDocument,
  SeoDocumentFieldMappings,
  SeoDisabledPluginConfig,
  SeoEnabledPluginConfig,
  SeoGeneratedNames,
  SeoPluginAccess,
  SeoPluginConfig,
  SeoSchemaType,
  SeoSitemapConfig,
  SeoPayload,
  SeoRobotsDirectives,
  SeoSocialMetadata,
  ResolvedSeoMetadata,
} from '../types.js'
